package com.afap.discuz.chh.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.afap.discuz.chh.greendao.CategoryListAtom;

import com.afap.discuz.chh.greendao.CategoryListAtomDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryListAtomDaoConfig;

    private final CategoryListAtomDao categoryListAtomDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryListAtomDaoConfig = daoConfigMap.get(CategoryListAtomDao.class).clone();
        categoryListAtomDaoConfig.initIdentityScope(type);

        categoryListAtomDao = new CategoryListAtomDao(categoryListAtomDaoConfig, this);

        registerDao(CategoryListAtom.class, categoryListAtomDao);
    }
    
    public void clear() {
        categoryListAtomDaoConfig.getIdentityScope().clear();
    }

    public CategoryListAtomDao getCategoryListAtomDao() {
        return categoryListAtomDao;
    }

}
