package com.afap.discuz.chh.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY_LIST_ATOM".
 */
public class CategoryListAtom {

    private String cat;
    private String href;
    private String title;
    private String content;
    private String time;
    private String thumb_url;

    public CategoryListAtom() {
    }

    public CategoryListAtom(String cat, String href, String title, String content, String time, String thumb_url) {
        this.cat = cat;
        this.href = href;
        this.title = title;
        this.content = content;
        this.time = time;
        this.thumb_url = thumb_url;
    }

    public String getCat() {
        return cat;
    }

    public void setCat(String cat) {
        this.cat = cat;
    }

    public String getHref() {
        return href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getThumb_url() {
        return thumb_url;
    }

    public void setThumb_url(String thumb_url) {
        this.thumb_url = thumb_url;
    }

}
